name: Update Rust Toolchain

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-rust-toolchain:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Update rust-toolchain
        id: update-rust-toolchain
        run: |
          version="$(rustc +stable -V | awk '{ print $2 }')"
          cat > ./rust-toolchain <<< "$version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update rust-toolchain to ${{ steps.update-rust-toolchain.outputs.version }}
          branch: update-rust-toolchain-to-${{ steps.update-rust-toolchain.outputs.version }}
          delete-branch: true
          title: Update rust-toolchain to ${{ steps.update-rust-toolchain.outputs.version }}
